unique_ids:
  assets:
    standard-page.html: ZNFV7IRAWZUGWD6WTZQANQI374PLUMSL
    theme.css: A6CBJPOF2MCH6VD2GIEWFZL6CD24VHJT
  forms:
    DatePickerDialog: '1737383652922163862896710.21225'
    Index: N2WSI3M67OH7U46BEGHAGUJY3EZDU3O6
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '173116239125999946925327.00089'
