unique_ids:
  assets:
    standard-page.html: ZNFV7IRAWZUGWD6WTZQANQI374PLUMSL
    theme.css: A6CBJPOF2MCH6VD2GIEWFZL6CD24VHJT
  forms:
    Form1: N2WSI3M67OH7U46BEGHAGUJY3EZDU3O6
  modules: {}
  scripts: {}
  server_modules: {}
